import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { Navbar } from "@/components/Navbar";

const diatype = localFont({ src: "./fonts/ABCDiatypeRegular.woff2", display: "swap" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={diatype.className}>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	);
}
